apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: localhost:5000/engine:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  selector:
    app: engine
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

